[Troubleshooting]
ignored_applications=@Invalid()
force_raster_widgets=1

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x5?\0\0\x3\x30\0\0\0\0\0\0\0\0\0\0\x2\xf2\0\0\x3\x30\0\0\0\0\x2\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\x5?\0\0\x3\x30)

[Appearance]
standard_dialogs=xdgdesktopportal
style=kvantum
custom_palette=true

[Interface]
gui_effects=General, AnimateMenu, AnimateCombo, AnimateTooltip, AnimateToolBox
stylesheets=@Invalid()
keyboard_scheme=3
double_click_interval=400
toolbutton_style=4
menus_have_icons=true
show_shortcuts_in_context_menus=true
dialog_buttons_have_icons=1
activate_item_on_single_click=1
wheel_scroll_lines=3
cursor_flash_time=1000
buttonbox_layout=2
underline_shortcut=1

[Fonts]
fixed="CaskaydiaCove Nerd Font Mono,12,-1,5,50,0,0,0,0,0"
general="CaskaydiaCove Nerd Font,11,-1,5,50,0,0,0,0,0"
