color0 #46464d
color1 #ffb4ab
color2 #cacfee
color3 #c5c5d3
color4 #ebc6e0
color5 #bfc5e4
color6 #c5c5d3
color7 #e5e2e4
color8 #909098
color9 #ffb4ab
color10 #cacfee
color11 #c5c5d3
color12 #ebc6e0
color13 #bfc5e4
color14 #c5c5d3
color15 #e5e2e4

cursor                #e5e2e4
cursor_text_color     #131315
background            #131315
foreground            #e5e2e4
selection_foreground  #c6c6ce
selection_background  #46464d
active_border_color   #cacfee
inactive_border_color #46464d
url_color             #cacfee

active_tab_foreground   #292f47
active_tab_background   #cacfee
inactive_tab_foreground #c6c6ce
inactive_tab_background #46464d
cursor_trail_color      #c6c6ce
