color0 #21302e
color1 #fd4663
color2 #75d7c6
color3 #6ba8c7
color4 #7584c8
color5 #a1ded3
color6 #a3c9dc
color7 #f2f3f3
color8 #5e6e6c
color9 #fd4663
color10 #75d7c6
color11 #6ba8c7
color12 #7584c8
color13 #a1ded3
color14 #a3c9dc
color15 #f2f3f3

cursor                #f2f3f3
cursor_text_color     #1a2322
background            #1a2322
foreground            #f2f3f3
selection_foreground  #afb6b5
selection_background  #21302e
active_border_color   #75d7c6
inactive_border_color #21302e
url_color             #75d7c6

active_tab_foreground   #1b2221
active_tab_background   #75d7c6
inactive_tab_foreground #afb6b5
inactive_tab_background #21302e
cursor_trail_color      #afb6b5
