-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Nordzy-cursors")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    cursor = {
        persistent_warps = true,
    },
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("discover-overlay")
end)
