#!/usr/bin/env bash
# dynamic-rules.sh — generic dynamic rule editor for niri
# Generates window-rule or layer-rule entries in modules/75-dynamic.kdl
# Usage: dynamic-rules.sh [--window|--layer] [--screencast|--capture] [--add|--remove|--toggle]
#        Default is --window --screencast --toggle
set -euo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
source "$DIR/helpers.sh"
require_niri

CONFIG_DIR="$HOME/.config/niri"
DYNAMIC_FILE="$CONFIG_DIR/modules/dynamic.kdl"

RULE_TYPE="window"
BLOCK_TARGET="screencast"
ACTION="toggle"
APP_ID_OVERRIDE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
  --window)
    RULE_TYPE="window"
    shift
    ;;
  --layer)
    RULE_TYPE="layer"
    shift
    ;;
  --screencast)
    BLOCK_TARGET="screencast"
    shift
    ;;
  --capture)
    BLOCK_TARGET="screen-capture"
    shift
    ;;
  --add)
    ACTION="add"
    shift
    ;;
  --remove)
    ACTION="remove"
    shift
    ;;
  --toggle)
    ACTION="toggle"
    shift
    ;;
  --app-id)
    APP_ID_OVERRIDE="$2"
    shift 2
    ;;
  *)
    echo "Unknown arg $1"
    exit 1
    ;;
  esac
done

# Cache per rule type
CACHE_BASE="${XDG_CACHE_HOME:-$HOME/.cache}/niri-blocked"
CACHE_FILE="$CACHE_BASE/${RULE_TYPE}-blocked"
mkdir -p "$(dirname "$CACHE_FILE")"
touch "$CACHE_FILE"

if [[ "$RULE_TYPE" == "window" ]]; then
  if [[ -n "$APP_ID_OVERRIDE" ]]; then
    app_id="$APP_ID_OVERRIDE"
    title="\n$app_id"
  else
    json=$(niri_json focused-window)
    app_id=$(printf '%s' "$json" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('app_id',''))" 2>/dev/null || echo "")
    title=$(printf '%s' "$json" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('title',''))" 2>/dev/null || echo "window")
    if [[ -z "$app_id" ]]; then
      notify "Dynamic Rule" "No focused window with app-id" "low"
      exit 0
    fi
  fi
  # Use app-id only; titles for terminals change constantly
  target="$app_id"
  action_label="\n$app_id"
elif [[ "$RULE_TYPE" == "layer" ]]; then
  # For layer rules we need a namespace. Use a simple default or first layer.
  # Pick first layer surface namespace as target for demo; user can edit cache directly.
  json=$(niri_json layers)
  ns=$(printf '%s' "$json" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d[0].get('namespace','') if isinstance(d,list) and d else '')" 2>/dev/null || echo "")
  if [[ -z "$ns" ]]; then
    # fallback to a common notification namespace
    ns="*notification*"
  fi
  target="$ns"
  match_line="match namespace=\"$target\""
  action_label="\nlayer $target"
else
  notify "Dynamic Rule" "Unsupported rule type" "low"
  exit 1
fi

# Add/Remove/Toggle target in cache
case "$ACTION" in
add)
  if ! grep -Fxq "$target" "$CACHE_FILE" 2>/dev/null; then
    echo "$target" >>"$CACHE_FILE"
  fi
  action="Disabled"
  ;;
remove)
  if grep -Fxq "$target" "$CACHE_FILE" 2>/dev/null; then
    grep -Fxv "$target" "$CACHE_FILE" >"$CACHE_FILE.tmp" || true
    mv "$CACHE_FILE.tmp" "$CACHE_FILE"
  fi
  action="Enabled"
  ;;
toggle)
  if grep -Fxq "$target" "$CACHE_FILE" 2>/dev/null; then
    grep -Fxv "$target" "$CACHE_FILE" >"$CACHE_FILE.tmp" || true
    mv "$CACHE_FILE.tmp" "$CACHE_FILE"
    action="Enabled"
  else
    echo "$target" >>"$CACHE_FILE"
    action="Disabled"
  fi
  ;;
esac

# Rebuild dynamic file
tmp=$(mktemp)
{
  cat <<'EOF'
// Dynamic window/layer rules managed by scripts
// This file is hot-reloaded by niri when modified.
// Generated by dynamic-rules.sh
//
EOF
  # Window rules
  if [[ -f "$CACHE_BASE/window-blocked" ]]; then
    while IFS= read -r app_id || [[ -n $app_id ]]; do
      [[ -z "$app_id" ]] && continue
      esc_app=$(printf '%s' "$app_id" | sed 's/"/\\"/g')
      cat <<EOF
window-rule {
    match app-id="$esc_app"
    block-out-from "$BLOCK_TARGET"
}
EOF
    done <"$CACHE_BASE/window-blocked"
  fi
  # Layer rules
  if [[ -f "$CACHE_BASE/layer-blocked" ]]; then
    while IFS= read -r ns || [[ -n $ns ]]; do
      [[ -z "$ns" ]] && continue
      cat <<EOF
layer-rule {
    match namespace="$ns"
    block-out-from "$BLOCK_TARGET"
}
EOF
    done <"$CACHE_BASE/layer-blocked"
  fi
} >"$tmp"
mv "$tmp" "$DYNAMIC_FILE"

notify "Dynamic $RULE_TYPE rule" "$ACTION ${BLOCK_TARGET} for $action_label — ${action}" "low"
