# ==================================================
#  KoolDots (2026)
#  Project URL: https://github.com/LinuxBeginnings
#  License: GNU GPLv3
#  SPDX-License-Identifier: GPL-3.0-or-later
# ==================================================
# Commands and Apps to be executed at launch
exec-once = hyprctl output create headless
exec-once = hyprpm enable dynamic-cursors

exec-once = sh -c 'sleep 2 && systemctl --user start sunshine'

exec-once = pm2 resurrect
