# ==================================================
#  KoolDots (2026)
#  Project URL: https://github.com/LinuxBeginnings
#  License: GNU GPLv3
#  SPDX-License-Identifier: GPL-3.0-or-later
# ==================================================
# User Settings
# This is where you put your own settings as this will not be touched during update 
# if the upgrade.sh is used.

# refer to Hyprland wiki for more info https://wiki.hyprland.org/Configuring/Variables/
# NOTE: some settings are in ~/.config/hypr/UserConfigs/UserDecorAnimations.conf
#
# Look on ~/.config/hypr/configs/SystemSettings.conf to know how to modify this

plugin:dynamic-cursors {
  enabled = true
  mode = tilt
  threshold = 2

  rotate {
    length = 24
    offset = 0.0
  }

  tilt {
    limit = 5000
    activation = negative_quadratic
    window = 100
    full = 120
  }

  stretch {

    # controls how much the cursor is stretched
    # this value controls at which speed (px/s) the full stretch is reached
    # the full stretch being twice the original length
    limit = 3000

    # relationship between speed and stretch amount, supports these values:
    # linear             - a linear function is used
    # quadratic          - a quadratic function is used
    # negative_quadratic - negative version of the quadratic one, feels more aggressive
    # see `activation` in `src/mode/utils.cpp` for how exactly the calculation is done
    activation = quadratic

    # time window (ms) over which the speed is calculated
    # higher values will make slow motions smoother but more delayed
    window = 100
  }

  shake {
    enabled = false
    threshold = 6.0
    base = 4.0
    speed = 4.0
    influence = 0.0
    limit = 0.0
    timeout = 2000
    effects = false
    ipc = false
  }

  hyprcursor {
    nearest = true
    enabled = true
    resolution = -1
    fallback = clientside
  }
}

