# ==================================================
#  KoolDots (2026)
#  Project URL: https://github.com/LinuxBeginnings
#  License: GNU GPLv3
#  SPDX-License-Identifier: GPL-3.0-or-later
# ==================================================
# For window rules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates

windowrule = match:class ^(discord|Discord|webcord|vesktop)$, workspace 2
windowrule = match:class ^(ai.opencode.desktop)$, workspace 4
windowrule = match:class ^([Bb]rave-browser(-beta|-dev|-unstable)?)$, workspace 3
windowrule = match:class ^(steam_app_1313140)$, no_screen_share on


# Layer rules now belong in UserConfigs/LayerRules.conf

