local configHome = os.getenv("XDG_CONFIG_HOME") or (os.getenv("HOME") .. "/.config")
local hyprDir = configHome .. "/hypr"

HYPR_BASE_DIR = hyprDir

-- Generated by Noctalia templates
-- For Noctalia Color templates
require("noctalia").apply_theme()

-- Setup config
require("setup")

-- HyprMod managed settings
require("hyprland-gui")
