-- Hyprlock config for < 1080p monitor resolutions
-- Original config submitted by https://github.com/SherLock707

-- Sourcing colors generated by wallust
dofile(os.getenv("HOME") .. "/.config/hypr/wallust/wallust-hyprland.conf")

local Scripts = os.getenv("HOME") .. "/.config/hypr/scripts"

hl.config({
	general = {
		fractional_scaling = 2,
		immediate_render = true,
	},
})

hl.background({
	monitor = "",
	path = os.getenv("HOME") .. "/.config/hypr/wallpaper_effects/.wallpaper_current",
	color = "rgb(0,0,0)",
	blur_size = 3,
	blur_passes = 2,
	noise = 0.0117,
	contrast = 1.3000,
	brightness = 0.8000,
	vibrancy = 0.2100,
	vibrancy_darkness = 0.0,
})

-- Date
hl.label({
	monitor = "",
	text = 'cmd[update:18000000] echo "<b> "$(date +\'%A, %-d %B\')" </b>"',
	color = color13,
	font_size = 48,
	font_family = "Victor Mono Bold Italic",
	position = "0, -60",
	halign = "center",
	valign = "center",
})

-- Hour-Time
hl.label({
	monitor = "",
	text = 'cmd[update:1000] echo "$(date +"%I:%M %p")"',
	color = color8,
	font_size = 130,
	font_family = "JetBrainsMono Nerd Font ExtraBold",
	position = "0, -250",
	halign = "center",
	valign = "top",
})

-- USER
hl.label({
	monitor = "",
	text = " " .. (os.getenv("USER") or ""),
	color = color9,
	font_size = 36,
	font_family = "Victor Mono Bold Oblique",
	position = "0, 275",
	halign = "center",
	valign = "bottom",
})

-- INPUT FIELD
hl.input_field({
	monitor = "",
	size = "230, 70",
	outline_thickness = 2,
	dots_size = 0.2,
	dots_spacing = 0.2,
	dots_center = true,
	outer_color = color8,
	inner_color = "rgba(255, 255, 255, 0.1)",
	capslock_color = "rgb(255,255,255)",
	font_color = color13,
	fade_on_empty = false,
	font_family = "Victor Mono Bold Oblique",
	placeholder_text = '<i><span foreground="##ffffff99">🔒 Type Password</span></i>',
	hide_input = false,
	position = "0, 100",
	halign = "center",
	valign = "bottom",
})

-- Keyboard LAYOUT
hl.label({
	monitor = "",
	text = "$LAYOUT",
	color = color8,
	font_size = 14,
	font_family = "Victor Mono Bold Oblique",
	position = "0, 70",
	halign = "center",
	valign = "bottom",
})

-- uptime
hl.label({
	monitor = "",
	text = 'cmd[update:60000] echo "<b> "$(uptime -p || ' .. Scripts .. '/UptimeNixOS.sh)" </b>"',
	color = color8,
	font_size = 24,
	font_family = "Victor Mono Bold Oblique",
	position = "0, 0",
	halign = "right",
	valign = "bottom",
})

-- battery information
hl.label({
	monitor = "",
	text = 'cmd[update:1000] echo "<b> "$(' .. Scripts .. '/Battery.sh)" </b>"',
	color = color8,
	font_size = 16,
	font_family = "Victor Mono Bold Oblique",
	position = "0, 30",
	halign = "right",
	valign = "bottom",
})

-- weather
hl.label({
	monitor = "",
	text = 'cmd[update:3600000] [ -f "$HOME/.cache/.weather_cache" ] && cat "$HOME/.cache/.weather_cache"',
	color = color8,
	font_size = 14,
	font_family = "Victor Mono Bold Oblique",
	position = "50, 0",
	halign = "left",
	valign = "bottom",
})
