# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E8DBD3
background         #161622
cursor             #E8DBD3

active_tab_foreground     #161622
active_tab_background     #E8DBD3
inactive_tab_foreground   #E8DBD3
inactive_tab_background   #161622

active_border_color   #E8DBD3
inactive_border_color #161622
bell_border_color     #1F2029

color0      #161622
color1		#1F2029
color2		#524E5E
color3		#5A534F
color4		#5E5D72
color5		#715D75
color6		#707C60
color7		#E8DBD3
color8		#2A2A37
color9		#363849
color10		#918BA7
color11		#A0948C
color12		#A8A5CB
color13		#C9A5D0
color14		#C8DEAB
color15		#E8DBD3
