# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E6DAD0
background         #3C3E4F
cursor             #E6DAD0

active_tab_foreground     #3C3E4F
active_tab_background     #E6DAD0
inactive_tab_foreground   #E6DAD0
inactive_tab_background   #3C3E4F

active_border_color   #E6DAD0
inactive_border_color #3C3E4F
bell_border_color     #32343E

color0      #3C3E4F
color1		#32343E
color2		#434552
color3		#695A67
color4		#825661
color5		#7C5F68
color6		#6D6674
color7		#E6DAD0
color8		#535567
color9		#575C6F
color10		#777B91
color11		#BAA0B7
color12		#E799AC
color13		#DEA9B9
color14		#C1B6CD
color15		#E6DAD0
