#!/usr/bin/env bash
# fz: run a command in a floating kitty window (stays open until a keypress)
# usage: fz [options] <command...>
#        fz -c 'command' [--title TITLE] [--size WxH]
# options: -c/--command, -t/--title, -s/--size (must precede the command)
set -u

title=""
size="1100 700"
cmd=""

while (( $# )); do
    case "$1" in
        -c|--command)
            if (( $# < 2 )); then echo "fz: missing command" >&2; exit 1; fi
            cmd="$2"; shift 2 ;;
        --title|-t)
            if (( $# < 2 )); then echo "fz: missing title" >&2; exit 1; fi
            title="$2"; shift 2 ;;
        --size|-s)
            if (( $# < 2 )); then echo "fz: missing size" >&2; exit 1; fi
            size="$2"; shift 2 ;;
        --)
            shift; cmd="$*"; break ;;
        *)
            cmd="$*"; break ;;
    esac
done

if [[ -z "$cmd" ]]; then
    echo "usage: fz [options] <command...> | fz -c 'command' [--title TITLE] [--size WxH]" >&2
    exit 1
fi

escaped=${cmd//\\/\\\\}
escaped=${escaped//\"/\\\"}

lua="Utils.eval_float_hold(\"$escaped\""
if [[ -n "$title" ]]; then
    lua+=", { title = \"$title\", size = \"$size\" }"
else
    lua+=", { size = \"$size\" }"
fi
lua+=")"

hyprctl eval "$lua"