#!/usr/bin/env bash
set -euo pipefail

# install-hyperfluent-grub.sh - Install GRUB + HyperFluent (Arch) on ESP=/boot
# Preserves: linux-cachyos as default (saved), linux as backup
# ESP is /boot (vfat 1G) - GRUB installed to --efi-directory=/boot --bootloader-id=GRUB
# Keeps systemd-boot as fallback (Boot0000) - does NOT run bootctl remove
# Theme: Coopydood/HyperFluent-GRUB-Theme arch variant at 1920x1080
# Run as root: sudo ~/Scripts/install-hyperfluent-grub.sh [--yes] [--theme-only]

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
log()  { echo -e "${CYAN}[INFO]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()  { echo -e "${RED}[ERR]${NC} $*" >&2; }
ok()   { echo -e "${GREEN}[OK]${NC} $*"; }

# --- config ---
ESP="/boot"
GRUB_DIR="/boot/grub"
THEME_DIR="/boot/grub/themes/hyperfluent"
GRUB_CFG="/boot/grub/grub.cfg"
ETC_GRUB="/etc/default/grub"
BACKUP_BASE="/root/.grub-install-backup"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
BACKUP_DIR="${BACKUP_BASE}-${TIMESTAMP}"
REPO_URL="https://github.com/Coopydood/HyperFluent-GRUB-Theme.git"
TMP_CLONE="/tmp/hyperfluent-grub-$$"
AUTO_YES=false
THEME_ONLY=false

for arg in "$@"; do case "$arg" in
  --yes|-y) AUTO_YES=true ;;
  --theme-only) THEME_ONLY=true ;;
  --help|-h) echo "Usage: $0 [--yes] [--theme-only]"; echo "  --yes        skip confirmations"; echo "  --theme-only only reinstall theme (skip grub-install)"; exit 0 ;;
esac; done

need_root() {
  if [[ $EUID -ne 0 ]]; then err "Run as root: sudo $0"; exit 1; fi
}

confirm() {
  $AUTO_YES && return 0
  read -rp "$1 [y/N]: " ans
  [[ "$ans" == "y" || "$ans" == "Y" ]]
}

need_root

log "ESP=$ESP  GRUB_DIR=$GRUB_DIR  THEME_DIR=$THEME_DIR"
log "Backup dir: $BACKUP_DIR"
echo ""

# --- preflight ---
if [[ ! -d /sys/firmware/efi ]]; then err "Not in UEFI mode (/sys/firmware/efi missing)"; exit 1; fi
if ! command -v efibootmgr &>/dev/null; then warn "efibootmgr not found - will install"; fi
if ! mountpoint -q "$ESP"; then warn "$ESP not mounted? check /etc/fstab"; fi
df -h "$ESP"
AVAIL_MB=$(df -m "$ESP" | awk 'NR==2{print $4}')
if [[ "$AVAIL_MB" -lt 150 ]]; then err "ESP free <150M ($AVAIL_MB M) - HyperFluent needs ~50M + grub 40M"; exit 1; fi
log "Preflight OK - $(df -h "$ESP" | tail -1)"

if [[ -d "$GRUB_DIR" && "$THEME_ONLY" == false ]]; then
  warn "$GRUB_DIR already exists - grub may be installed"
  efibootmgr -v | head -n 20 || true
fi

# show current bootloader
echo ""
log "Current bootloader:"
bootctl status 2>&1 | head -n 30 || true
echo ""
efibootmgr -v | head -n 15
echo ""

if ! confirm "Proceed to install GRUB + HyperFluent (cachy default, 1080p, keep systemd-boot fallback)?"; then
  log "Aborted"; exit 0
fi

# --- backup ---
log "Creating backup $BACKUP_DIR"
mkdir -p "$BACKUP_DIR"
efibootmgr -v > "$BACKUP_DIR/efibootmgr.before" 2>&1 || true
cp -a /boot/loader/loader.conf "$BACKUP_DIR/" 2>&1 || true
cp -a /boot/loader/entries "$BACKUP_DIR/" 2>&1 || true
if [[ -f "$ETC_GRUB" ]]; then cp -a "$ETC_GRUB" "$BACKUP_DIR/grub.before"; fi
tar czf "$BACKUP_DIR/esp-EFI-loader.tgz" -C / boot/EFI boot/loader 2>&1 || warn "tar backup failed"
log "Backup saved to $BACKUP_DIR"
ls -lh "$BACKUP_DIR"

# --- install packages ---
if [[ "$THEME_ONLY" == false ]]; then
  log "Installing packages: grub efibootmgr freetype2 git"
  pacman -S --needed --noconfirm grub efibootmgr freetype2 git
  ok "Packages OK"
else
  log "Theme-only: skipping package install"
fi

# --- grub-install (skip if theme-only or already installed and user wants skip) ---
if [[ "$THEME_ONLY" == false ]]; then
  if [[ -f "/boot/EFI/GRUB/grubx64.efi" ]]; then
    warn "GRUB EFI already at /boot/EFI/GRUB/grubx64.efi"
    if confirm "Re-run grub-install to update?"; then
      RUN_INSTALL=true
    else
      RUN_INSTALL=false
    fi
  else
    RUN_INSTALL=true
  fi

  if [[ "$RUN_INSTALL" == true ]]; then
    log "Running: grub-install --target=x86_64-efi --efi-directory=$ESP --bootloader-id=GRUB --recheck"
    grub-install --target=x86_64-efi --efi-directory="$ESP" --bootloader-id=GRUB --recheck
    ok "grub-install done"
    efibootmgr -v | head -n 20
    mkdir -p "$GRUB_DIR/themes"
  fi
else
  mkdir -p "$GRUB_DIR/themes"
fi

# --- /etc/default/grub ---
# Extract current cmdline for preservation (from loader entries or /proc/cmdline)
CMDLINE_DEFAULT="root=UUID=0c822fed-d153-4015-bf16-c6fdfc14c3d1 rw"
if [[ -f /boot/loader/entries/arch-linux-cachyos.conf ]]; then
  DETECTED=$(grep -E "^options" /boot/loader/entries/arch-linux-cachyos.conf | sed 's/^options //')
  if [[ -n "$DETECTED" ]]; then CMDLINE_DEFAULT="$DETECTED"; fi
fi
log "Using GRUB_CMDLINE_LINUX_DEFAULT=\"$CMDLINE_DEFAULT\""

if [[ ! -f "$ETC_GRUB" ]]; then
  log "Creating $ETC_GRUB"
  cat > "$ETC_GRUB" <<EOF
# /etc/default/grub - generated by install-hyperfluent-grub.sh $TIMESTAMP
GRUB_DEFAULT=saved
GRUB_SAVEDEFAULT=true
GRUB_TIMEOUT=5
GRUB_TIMEOUT_STYLE=menu
GRUB_DISTRIBUTOR="Arch"
GRUB_CMDLINE_LINUX_DEFAULT="$CMDLINE_DEFAULT"
GRUB_CMDLINE_LINUX=""
GRUB_PRELOAD_MODULES="part_gpt part_msdos"
GRUB_TERMINAL_OUTPUT=gfxterm
GRUB_GFXMODE=1920x1080,auto
GRUB_GFXPAYLOAD_LINUX=keep
GRUB_DISABLE_OS_PROBER=true
GRUB_THEME="$THEME_DIR/theme.txt"
GRUB_ENABLE_CRYPTODISK=n
EOF
  ok "Created $ETC_GRUB"
else
  log "Updating $ETC_GRUB (backup at $BACKUP_DIR/grub.before)"
  # helper to set or replace key
  set_grub_key() {
    local key="$1" val="$2" file="$ETC_GRUB"
    if grep -q "^${key}=" "$file"; then
      sed -i "s|^${key}=.*|${key}=\"${val}\"|" "$file"
      # handle unquoted
      sed -i "s|^${key}=.*|${key}=${val}|" "$file" 2>/dev/null || true
      # ensure quoted form
      if grep -q "^${key}=" "$file"; then
        sed -i "s|^${key}=.*|${key}=\"${val}\"|" "$file"
      fi
    else
      echo "${key}=\"${val}\"" >> "$file"
    fi
  }
  # ensure we have quoted values
  sed -i 's/^GRUB_DEFAULT=.*/GRUB_DEFAULT=saved/' "$ETC_GRUB" 2>/dev/null || echo 'GRUB_DEFAULT=saved' >> "$ETC_GRUB"
  grep -q "^GRUB_SAVEDEFAULT=" "$ETC_GRUB" || echo 'GRUB_SAVEDEFAULT=true' >> "$ETC_GRUB"
  sed -i 's/^GRUB_SAVEDEFAULT=.*/GRUB_SAVEDEFAULT=true/' "$ETC_GRUB"
  sed -i 's/^GRUB_TIMEOUT=.*/GRUB_TIMEOUT=5/' "$ETC_GRUB" 2>/dev/null || echo 'GRUB_TIMEOUT=5' >> "$ETC_GRUB"
  grep -q "^GRUB_TIMEOUT_STYLE=" "$ETC_GRUB" || echo 'GRUB_TIMEOUT_STYLE=menu' >> "$ETC_GRUB"
  sed -i 's/^GRUB_TIMEOUT_STYLE=.*/GRUB_TIMEOUT_STYLE=menu/' "$ETC_GRUB"
  sed -i 's/^GRUB_TERMINAL_OUTPUT=.*/GRUB_TERMINAL_OUTPUT=gfxterm/' "$ETC_GRUB" 2>/dev/null || echo 'GRUB_TERMINAL_OUTPUT=gfxterm' >> "$ETC_GRUB"
  if grep -q "^GRUB_GFXMODE=" "$ETC_GRUB"; then sed -i 's/^GRUB_GFXMODE=.*/GRUB_GFXMODE=1920x1080,auto/' "$ETC_GRUB"; else echo 'GRUB_GFXMODE=1920x1080,auto' >> "$ETC_GRUB"; fi
  grep -q "^GRUB_GFXPAYLOAD_LINUX=" "$ETC_GRUB" || echo 'GRUB_GFXPAYLOAD_LINUX=keep' >> "$ETC_GRUB"
  # theme line
  if grep -q "^GRUB_THEME=" "$ETC_GRUB"; then
    sed -i "s|^GRUB_THEME=.*|GRUB_THEME=\"$THEME_DIR/theme.txt\"|" "$ETC_GRUB"
  else
    echo "GRUB_THEME=\"$THEME_DIR/theme.txt\"" >> "$ETC_GRUB"
  fi
  # ensure cmdline preserved if not already set correctly
  if ! grep -q "0c822fed" "$ETC_GRUB"; then
    if grep -q "^GRUB_CMDLINE_LINUX_DEFAULT=" "$ETC_GRUB"; then
      sed -i "s|^GRUB_CMDLINE_LINUX_DEFAULT=.*|GRUB_CMDLINE_LINUX_DEFAULT=\"$CMDLINE_DEFAULT\"|" "$ETC_GRUB"
    else
      echo "GRUB_CMDLINE_LINUX_DEFAULT=\"$CMDLINE_DEFAULT\"" >> "$ETC_GRUB"
    fi
  fi
  ok "Updated $ETC_GRUB"
  echo "--- $ETC_GRUB ---"
  cat "$ETC_GRUB"
fi

# --- HyperFluent theme install ---
log "Installing HyperFluent (Arch variant) from $REPO_URL"
rm -rf "$TMP_CLONE"
if ! git clone --depth 1 "$REPO_URL" "$TMP_CLONE"; then
  err "git clone failed - check network or try: git clone $REPO_URL"
  exit 1
fi

if [[ ! -d "$TMP_CLONE/arch" ]]; then
  err "Clone missing arch/ folder - contents:"
  ls -l "$TMP_CLONE" | head
  exit 1
fi

log "Copying arch theme to $THEME_DIR"
rm -rf "$THEME_DIR"
mkdir -p "$(dirname "$THEME_DIR")"
cp -r "$TMP_CLONE/arch" "$THEME_DIR"
# some variants name folder "fluent" inside arch - ensure theme.txt at top
if [[ ! -f "$THEME_DIR/theme.txt" && -f "$THEME_DIR/arch/theme.txt" ]]; then
  cp -r "$THEME_DIR/arch"/* "$THEME_DIR"/
fi
# also handle packaged/ if needed (fallback)
if [[ ! -f "$THEME_DIR/theme.txt" ]]; then
  FOUND=$(find "$TMP_CLONE" -maxdepth 3 -name "theme.txt" | head -1)
  if [[ -n "$FOUND" ]]; then
    THEME_SRC_DIR=$(dirname "$FOUND")
    rm -rf "$THEME_DIR"
    cp -r "$THEME_SRC_DIR" "$THEME_DIR"
  fi
fi

if [[ ! -f "$THEME_DIR/theme.txt" ]]; then
  err "theme.txt not found at $THEME_DIR"
  ls -R "$THEME_DIR" | head -n 50
  exit 1
fi

ok "Theme copied to $THEME_DIR"
ls -lh "$THEME_DIR" | head -n 20
# sanitize absolute paths (gorgeous-grub style) - HyperFluent already relative but safe
sed -i -E 's|/boot/grub/themes/[^/]+/||g' "$THEME_DIR/theme.txt" 2>/dev/null || true
sed -i -E 's|/grub/themes/[^/]+/||g' "$THEME_DIR/theme.txt" 2>/dev/null || true

# --- optional gorgeous-grub-installer for future ---
if ! command -v gum &>/dev/null; then
  log "Tip: install 'gum' (paru -S gum) for gorgeous-grub-installer UI"
fi
log "To manage 45+ themes later: git clone https://github.com/FLEXIY0/gorgeous-grub-installer.git && ./gorgeous-grub.sh"

# --- generate grub.cfg ---
log "Generating $GRUB_CFG"
if ! grub-mkconfig -o "$GRUB_CFG"; then
  err "grub-mkconfig failed - check $ETC_GRUB"
  exit 1
fi
ok "Generated $GRUB_CFG"

# --- verification ---
echo ""
log "Verification:"
grub-script-check "$GRUB_CFG" && ok "grub-script-check passed" || warn "grub-script-check failed"
echo "--- menuentry ---"
grep -n "menuentry" "$GRUB_CFG" | head
echo "--- theme ---"
grep -n "theme\|gfxmode\|gfxpayload" "$GRUB_CFG" | head
echo "--- EFI boot order ---"
efibootmgr -v | head -n 20

# check that both kernels are present
if grep -q "vmlinuz-linux-cachyos" "$GRUB_CFG"; then ok "cachy kernel found in grub.cfg"; else warn "cachy kernel NOT in grub.cfg - check 10_linux"; fi
if grep -q "vmlinuz-linux " "$GRUB_CFG" || grep -q "vmlinuz-linux\"" "$GRUB_CFG"; then ok "stock kernel found"; else warn "stock kernel missing"; fi

echo ""
ok "Install complete!"
log "Backup at: $BACKUP_DIR"
log "Theme at: $THEME_DIR/theme.txt"
log "Config: $ETC_GRUB -> $GRUB_CFG"
log "systemd-boot kept as fallback - BIOS F12 can still select 'Linux Boot Manager' (Boot0000)"
log "Next: sudo grub-reboot 0  # test cachy once, then sudo reboot"
log "If theme not shown, check: grep GRUB_THEME $ETC_GRUB && ls -l $THEME_DIR/theme.txt"

rm -rf "$TMP_CLONE"
