local configHome = os.getenv("XDG_CONFIG_HOME") or (os.getenv("HOME") .. "/.config")
local HOME = os.getenv("HOME") or ""
-- ==================================================
--  KoolDots (2026)
--  Project URL: https://github.com/LinuxBeginnings
--  License: GNU GPLv3
--  SPDX-License-Identifier: GPL-3.0-or-later
-- ==================================================
-- Default Keybinds
-- visit https://wiki.hyprland.org/Configuring/Binds/ for more info

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local mainMod = "SUPER"
local scriptsDir = HOME .. "/.config/hypr/scripts"
local UserConfigs = HOME .. "/.config/hypr/UserConfigs"
local UserScripts = HOME .. "/.config/hypr/UserScripts"

-- settings for User defaults apps - set your default terminal and file manager on this file
-- Source: $UserConfigs/01-UserDefaults.conf — convert this file to Lua and ensure it is on Lua's package.path.
dofile(configHome .. "/hypr/UserConfigs/01-UserDefaults.lua")

--### STANDARD ####
-- Common shortcuts
--bindr = $mainMod, $mainMod_L, exec, pkill rofi || rofi -show drun -modi drun,filebrowser,run,window # Super Key to Launch rofi menu
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd("pkill rofi || true; " .. scriptsDir .. "/RofiFocusedWallpaperLink.sh >/dev/null 2>&1 || true; rofi -show drun -modi drun,filebrowser,run,window"), { description = "App launcher" })
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("xdg-open \"https://\""), { description = "Open default browser" })
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd(scriptsDir .. "/OverviewToggle.sh"), { description = "Desktop overview" })
--bindd = $mainMod, A, Ags overview, exec, pkill rofi || true && ags -t 'overview' # desktop overview (if installed)
--bindd = $mainMod, A, Quickshell overview, global, quickshell:overviewToggle # desktop overview (if installed)
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(scriptsDir .. "/LaunchTerminal.sh \"" .. term .. "\""), { description = "Open terminal" })
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(scriptsDir .. "/LaunchFileManager.sh \"" .. files .. "\" \"" .. term .. "\""), { description = "File manager" })
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd(scriptsDir .. "/rofi-ssh-menu.sh"), { description = "SSH session manager" })

-- FEATURES / EXTRAS
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(scriptsDir .. "/ThemeChanger.sh"), { description = "Global theme switcher using Wallust" })
hl.bind(mainMod .. " + H", hl.dsp.exec_cmd(scriptsDir .. "/KeyHints.sh"), { description = "Help / cheat sheet" })
hl.bind(mainMod .. " + ALT + R", hl.dsp.exec_cmd(scriptsDir .. "/Refresh.sh"), { description = "Refresh bar and menus" })
hl.bind(mainMod .. " + ALT + E", hl.dsp.exec_cmd(scriptsDir .. "/RofiEmoji.sh"), { description = "Emoji menu" })
hl.bind(mainMod .. " + S", hl.dsp.exec_cmd(scriptsDir .. "/RofiSearch.sh"), { description = "Web search" })
hl.bind(mainMod .. " + CTRL + S", hl.dsp.exec_cmd(scriptsDir .. "/RofiFocusedWallpaperLink.sh >/dev/null 2>&1 || true; rofi -show window"), { description = "Window switcher" })
hl.bind(mainMod .. " + ALT + O", hl.dsp.exec_cmd(scriptsDir .. "/ChangeBlur.sh"), { description = "Toggle blur" })
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.exec_cmd(scriptsDir .. "/GameMode.sh"), { description = "Toggle game mode" })
hl.bind(mainMod .. " + ALT + L", hl.dsp.exec_cmd(scriptsDir .. "/ChangeLayout.sh toggle"), { description = "Toggle layouts" })
hl.bind(mainMod .. " + ALT + V", hl.dsp.exec_cmd(scriptsDir .. "/ClipManager.sh"), { description = "Clipboard manager" })
hl.bind(mainMod .. " + CTRL + R", hl.dsp.exec_cmd(scriptsDir .. "/RofiThemeSelector.sh"), { description = "Rofi theme selector" })
hl.bind(mainMod .. " + CTRL + SHIFT + R", hl.dsp.exec_cmd("pkill rofi || true && " .. scriptsDir .. "/RofiThemeSelector-modified.sh"), { description = "Rofi theme selector (modified)" })
hl.bind(mainMod .. " + Escape", hl.dsp.exec_cmd("hyprctl reload"), { description = "Reload Hyprland" })
hl.bind(mainMod .. " + CTRL + K", hl.dsp.exec_cmd(scriptsDir .. "/Kitty_themes.sh"), { description = "Kitty theme selector" })
hl.bind(mainMod .. " + CTRL + G", hl.dsp.exec_cmd(scriptsDir .. "/Ghostty_themes.sh"), { description = "Ghostty theme selector" })
hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd(UserScripts .. "/RainbowBorders-low-cpu.sh  --run-once"), { description = "Set static Rainbow Border" })
-- bindd = $mainMod SHIFT, H, Toggle Mute/Unmute for Active-Window, exec, $scriptsDir/Toggle-Active-Window-Audio.sh
hl.bind("ALT + SHIFT + S", hl.dsp.exec_cmd(scriptsDir .. "/hyprshot.sh -m region -o $HOME/Pictures/Screenshots"), { description = "Hyprshot Screen Capture" })

hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }), { description = "Fullscreen" })
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }), { description = "Maximize window" })
hl.bind(mainMod .. " + SPACE", hl.dsp.window.float({ action = "toggle" }), { description = "Float current window" })
hl.bind(mainMod .. " + ALT + SPACE", hl.dsp.exec_cmd(scriptsDir .. "/Float-all-Windows.sh"), { description = "Float all windows" })
-- NOTE: Dropterminal is currently certified only with kitty. Not all terminals behave correctly as a dropdown.
hl.bind(mainMod .. " + SHIFT + Return", hl.dsp.exec_cmd(scriptsDir .. "/Dropterminal.sh kitty"), { description = "DropDown terminal" })

-- Desktop zooming or magnifier
hl.bind(mainMod .. " + ALT + mouse_down", hl.dsp.exec_cmd("hyprctl keyword cursor:zoom_factor \"$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor * 2.0}')\""), { description = "Zoom in" })
hl.bind(mainMod .. " + ALT + mouse_up", hl.dsp.exec_cmd("hyprctl keyword cursor:zoom_factor \"$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor / 2.0}')\""), { description = "Zoom out" })

-- Waybar / Bar related
hl.bind(mainMod .. " + CTRL + ALT + B", hl.dsp.exec_cmd("pkill -SIGUSR1 waybar"), { description = "Toggle waybar on/off" })
hl.bind(mainMod .. " + CTRL + B", hl.dsp.exec_cmd(scriptsDir .. "/WaybarStyles.sh"), { description = "Waybar styles menu" })
hl.bind(mainMod .. " + ALT + B", hl.dsp.exec_cmd(scriptsDir .. "/WaybarLayout.sh"), { description = "Waybar layout menu" })

-- Night light toggle (Hyprsunset)
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd(scriptsDir .. "/Hyprsunset.sh toggle"), { description = "Toggle Hyprsunset - night light" })

-- FEATURES / EXTRAS (UserScripts)
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exec_cmd(UserScripts .. "/RofiBeats.sh"), { description = "Online music" })
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd(scriptsDir .. "/WallpaperSelect.sh"), { description = "Select Wallpaper" })
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd(scriptsDir .. "/WallpaperEffects.sh"), { description = "Wallpaper effects" })
hl.bind("CTRL + ALT + W", hl.dsp.exec_cmd(scriptsDir .. "/WallpaperRandom.sh"), { description = "Random wallpaper" })
hl.bind(mainMod .. " + CTRL + O", hl.dsp.window.set_prop({ prop = "opaque", value = "toggle", window = "active" }), { description = "Toggle active window opacity" })
hl.bind(mainMod .. " + SHIFT + slash", hl.dsp.exec_cmd(scriptsDir .. "/KeyBinds.sh"), { description = "Search keybinds" })
hl.bind(mainMod .. " + SHIFT + A", hl.dsp.exec_cmd(scriptsDir .. "/Animations.sh"), { description = "Animations menu" })
hl.bind(mainMod .. " + SHIFT + O", hl.dsp.exec_cmd(scriptsDir .. "/ZshChangeTheme.sh"), { description = "Change ZSH (oh-my-zsh) theme" })
hl.bind("ALT_L + SHIFT_L", hl.dsp.exec_cmd(scriptsDir .. "/KeyboardLayout.sh switch"), { locked = true, non_consuming = true, description = "Switch keyboard layout globally" })
hl.bind("SHIFT_L + ALT_L", hl.dsp.exec_cmd(scriptsDir .. "/Tak0-Per-Window-Switch.sh"), { locked = true, non_consuming = true, description = "Switch keyboard layout per-window" })
hl.bind(mainMod .. " + ALT + C", hl.dsp.exec_cmd(UserScripts .. "/RofiCalc.sh"), { description = "Calculator" })

-- Move current workspaces to monitors (left right up or down)
hl.bind(mainMod .. " + CTRL + F9", function() local w = hl.get_active_workspace(); if not w then return end; hl.dispatch(hl.dsp.workspace.move({ workspace = w.id, monitor = "l" })) end, { description = "Move workspace to left monitor" })
hl.bind(mainMod .. " + CTRL + F10", function() local w = hl.get_active_workspace(); if not w then return end; hl.dispatch(hl.dsp.workspace.move({ workspace = w.id, monitor = "r" })) end, { description = "Move workspace to right monitor" })
hl.bind(mainMod .. " + CTRL + F11", function() local w = hl.get_active_workspace(); if not w then return end; hl.dispatch(hl.dsp.workspace.move({ workspace = w.id, monitor = "u" })) end, { description = "Move workspace to up monitor" })
hl.bind(mainMod .. " + CTRL + F12", function() local w = hl.get_active_workspace(); if not w then return end; hl.dispatch(hl.dsp.workspace.move({ workspace = w.id, monitor = "d" })) end, { description = "Move workspace to down monitor" })

--### SYSTEM ####
hl.bind("CTRL + ALT + Delete", hl.dsp.exec_cmd(scriptsDir .. "/Logout.sh"), { description = "Exit Hyprland" })
hl.bind(mainMod .. " + Q", hl.dsp.window.close(), { description = "Close active window" })
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.exec_cmd(scriptsDir .. "/KillActiveProcess.sh"), { description = "Terminate active process" })
hl.bind("CTRL + ALT + L", hl.dsp.exec_cmd(scriptsDir .. "/LockScreen.sh"), { description = "Lock screen" })
hl.bind("CTRL + ALT + P", hl.dsp.exec_cmd(scriptsDir .. "/Wlogout.sh"), { description = "Powermenu" })
hl.bind(mainMod .. " + SHIFT + N", hl.dsp.exec_cmd("swaync-client -t -sw"), { description = "Notification panel" })
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd(scriptsDir .. "/Kool_Quick_Settings.sh"), { description = "Quick settings menu" })

-- Master Layout
hl.bind(mainMod .. " + CTRL + D", hl.dsp.layout("removemaster"), { description = "Remove master" })
hl.bind(mainMod .. " + I", hl.dsp.layout("addmaster"), { description = "Add master" })
-- j/k cycle windows (layout-aware)
hl.bind(mainMod .. " + J", hl.dsp.exec_cmd(scriptsDir .. "/LayoutKeybindDispatch.sh cycle-next"), { description = "Cycle next (layout-aware)" })
hl.bind(mainMod .. " + K", hl.dsp.exec_cmd(scriptsDir .. "/LayoutKeybindDispatch.sh cycle-prev"), { description = "Cycle previous (layout-aware)" })
hl.bind(mainMod .. " + CTRL + Return", hl.dsp.layout("swapwithmaster"), { description = "Swap with master" })

-- Dwindle Layout
hl.bind(mainMod .. " + SHIFT + I", hl.dsp.layout("togglesplit"), { description = "Toggle split (dwindle)" })
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo(), { description = "Toggle pseudo (dwindle)" })

-- Works on either layout (Master or Dwindle)
hl.bind(mainMod .. " + M", hl.dsp.layout("splitratio 0.3"), { description = "Set split ratio 0.3" })
-- legacy init hook kept for compatibility; keybind behavior is now resolved dynamically

-- Direct layout binds
hl.bind(mainMod .. " + ALT + 1", hl.dsp.exec_cmd(scriptsDir .. "/ChangeLayout.sh dwindle"), { description = "Layout dwindle" })
hl.bind(mainMod .. " + ALT + 2", hl.dsp.exec_cmd(scriptsDir .. "/ChangeLayout.sh master"), { description = "Layout master" })
hl.bind(mainMod .. " + ALT + 3", hl.dsp.exec_cmd(scriptsDir .. "/ChangeLayout.sh scrolling"), { description = "Layout scrolling" })
hl.bind(mainMod .. " + ALT + 4", hl.dsp.exec_cmd(scriptsDir .. "/ChangeLayout.sh monocle"), { description = "Layout monocle" })

-- Scrolling Layout 
hl.bind(mainMod .. " + SHIFT + period", hl.dsp.layout("move +col"), { description = "Move to right column" })
hl.bind(mainMod .. " + SHIFT + comma", hl.dsp.layout("move -col"), { description = "Move to left column" })
hl.bind(mainMod .. " + ALT + comma", hl.dsp.layout("swapcol l"), { description = "Swap columns left" })
hl.bind(mainMod .. " + ALT + period", hl.dsp.layout("swapcol r"), { description = "Swap columns right" })
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("bash " .. scriptsDir .. "/ScrollCycleColumnWidth.sh"), { description = "Cycle column width preset (scrolling)" })

-- Set layout to Horizontal (Standard "Tape" style)
hl.bind(mainMod .. " + ALT + H", hl.dsp.exec_cmd("hyprctl keyword scrolling:direction right"), { description = "Horizonal scroll right" })
-- Set layout to Vertical (Stacked "Column" style)
hl.bind(mainMod .. " + ALT + V", hl.dsp.exec_cmd("hyprctl keyword scrolling:direction down"), { description = "Vertical Scroll down" })
-- Create a toggle bind (e.g., Mod + Shift + S)
hl.bind(mainMod .. " + ALT + S", hl.dsp.exec_cmd("bash -c '[[ $(hyprctl getoption scrolling:direction -j | jq -r \".str\") == \"right\" ]] && hyprctl keyword scrolling:direction down || hyprctl keyword scrolling:direction right'"), { description = "Toggle scrolling V/H" })

-- Cycle windows; if floating bring to top
hl.bind("ALT + Tab", hl.dsp.window.cycle_next({ next = true }), { description = "Cycle next window" })
hl.bind("ALT + Tab", hl.dsp.window.bring_to_top(), { description = "Bring active to top" })

-- Special Keys / Hot Keys
hl.bind("xf86audioraisevolume", hl.dsp.exec_cmd(scriptsDir .. "/Volume.sh --inc"), { locked = true, repeating = true, description = "Volume up" })
hl.bind("xf86audiolowervolume", hl.dsp.exec_cmd(scriptsDir .. "/Volume.sh --dec"), { locked = true, repeating = true, description = "Volume down" })
hl.bind("ALT + xf86audioraisevolume", hl.dsp.exec_cmd(scriptsDir .. "/Volume.sh --inc-precise"), { locked = true, repeating = true, description = "Volume up precise" })
hl.bind("ALT + xf86audiolowervolume", hl.dsp.exec_cmd(scriptsDir .. "/Volume.sh --dec-precise"), { locked = true, repeating = true, description = "Volume down precise" })
hl.bind("xf86AudioMicMute", hl.dsp.exec_cmd(scriptsDir .. "/Volume.sh --toggle-mic"), { locked = true, description = "Toggle mic mute" })
hl.bind("xf86audiomute", hl.dsp.exec_cmd(scriptsDir .. "/Volume.sh --toggle"), { locked = true, description = "Toggle mute" })
hl.bind("xf86Sleep", hl.dsp.exec_cmd("systemctl suspend"), { locked = true, description = "Sleep" })
hl.bind("xf86Rfkill", hl.dsp.exec_cmd(scriptsDir .. "/AirplaneMode.sh"), { locked = true, description = "Airplane mode" })

-- media controls using keyboards
hl.bind("xf86AudioPlayPause", hl.dsp.exec_cmd(scriptsDir .. "/MediaCtrl.sh --pause"), { locked = true, description = "Play/pause" })
hl.bind("xf86AudioPause", hl.dsp.exec_cmd(scriptsDir .. "/MediaCtrl.sh --pause"), { locked = true, description = "Pause" })
hl.bind("xf86AudioPlay", hl.dsp.exec_cmd(scriptsDir .. "/MediaCtrl.sh --pause"), { locked = true, description = "Play" })
hl.bind("xf86AudioNext", hl.dsp.exec_cmd(scriptsDir .. "/MediaCtrl.sh --nxt"), { locked = true, description = "Next track" })
hl.bind("xf86AudioPrev", hl.dsp.exec_cmd(scriptsDir .. "/MediaCtrl.sh --prv"), { locked = true, description = "Previous track" })
hl.bind("xf86audiostop", hl.dsp.exec_cmd(scriptsDir .. "/MediaCtrl.sh --stop"), { locked = true, description = "Stop" })

-- Screenshot keybindings NOTE: You may need to press Fn key as well
hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd(scriptsDir .. "/ScreenShot.sh --now"), { description = "Screenshot now" })
hl.bind(mainMod .. " + SHIFT + Print", hl.dsp.exec_cmd(scriptsDir .. "/ScreenShot.sh --area"), { description = "Screenshot (area)" })
hl.bind(mainMod .. " + CTRL + Print", hl.dsp.exec_cmd(scriptsDir .. "/ScreenShot.sh --in5"), { description = "Screenshot in 5s" })
hl.bind(mainMod .. " + CTRL + SHIFT + Print", hl.dsp.exec_cmd(scriptsDir .. "/ScreenShot.sh --in10"), { description = "Screenshot in 10s" })
hl.bind("ALT + Print", hl.dsp.exec_cmd(scriptsDir .. "/ScreenShot.sh --active"), { description = "Screenshot active window" })

-- screenshot with swappy (another screenshot tool)
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd(scriptsDir .. "/ScreenShot.sh --swappy"), { description = "Screenshot (swappy)" })

-- Resize windows
hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.resize({ x = -50, y = 0, relative = true }), { repeating = true, description = "Resize left (-50)" })
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.resize({ x = 50, y = 0, relative = true }), { repeating = true, description = "Resize right (+50)" })
hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.resize({ x = 0, y = -50, relative = true }), { repeating = true, description = "Resize up (-50)" })
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.resize({ x = 0, y = 50, relative = true }), { repeating = true, description = "Resize down (+50)" })

-- Move windows
hl.bind(mainMod .. " + CTRL + left", hl.dsp.window.move({ direction = "l" }), { description = "Move window left" })
hl.bind(mainMod .. " + CTRL + right", hl.dsp.window.move({ direction = "r" }), { description = "Move window right" })
hl.bind(mainMod .. " + CTRL + up", hl.dsp.window.move({ direction = "u" }), { description = "Move window up" })
hl.bind(mainMod .. " + CTRL + down", hl.dsp.window.move({ direction = "d" }), { description = "Move window down" })

hl.bind(mainMod .. " + CTRL + H", hl.dsp.window.move({ direction = "l" }), { description = "Move window left" })
hl.bind(mainMod .. " + CTRL + L", hl.dsp.window.move({ direction = "r" }), { description = "Move window right" })
hl.bind(mainMod .. " + CTRL + K", hl.dsp.window.move({ direction = "u" }), { description = "Move window up" })
hl.bind(mainMod .. " + CTRL + J", hl.dsp.window.move({ direction = "d" }), { description = "Move window down" })

-- Swap windows
hl.bind(mainMod .. " + ALT + left", hl.dsp.window.swap({ direction = "l" }), { description = "Swap window left" })
hl.bind(mainMod .. " + ALT + right", hl.dsp.window.swap({ direction = "r" }), { description = "Swap window right" })
hl.bind(mainMod .. " + ALT + up", hl.dsp.window.swap({ direction = "u" }), { description = "Swap window up" })
hl.bind(mainMod .. " + ALT + down", hl.dsp.window.swap({ direction = "d" }), { description = "Swap window down" })

-- group
hl.bind(mainMod .. " + G", hl.dsp.group.toggle(), { description = "Toggle group" })

-- Navigate within a group
hl.bind(mainMod .. " + Tab", hl.dsp.group.next(), { description = "Change Group Forward" })
-- TODO: manual review on line 196 — changegroupactive: expected 'f', 'b', or an index (got "")
-- hl.bind(mainMod .. " + CTRL + tab", hl.dsp.changegroupactive(), { description = "Change active in group" })
hl.bind(mainMod .. " + SHIFT + Tab", hl.dsp.group.prev(), { description = "Change Group Back" })

-- Move window into/out of group
hl.bind(mainMod .. " + CTRL + K", hl.dsp.window.move({ into_group = "l" }), { description = "Move left into group" })
hl.bind(mainMod .. " + CTRL + L", hl.dsp.window.move({ into_group = "r" }), { description = "Move Right into group" })
hl.bind(mainMod .. " + CTRL + H", hl.dsp.window.move({ out_of_group = true }), { description = "Move active out of group" })

-- Try to dynamically move in grouped window and when ungrouped
--  Not working for me DW 11/26/25  PR: https://github.com/LinuxBeginnings/Hyprland-Dots/pull/872
--bindd = $mainMod, right, Focus right, exec, bash -c 'if hyprctl activewindow -j | jq -e "((.grouped | type) == \"boolean\") or (.address == (.grouped[-1] // empty))" >/dev/null 2>&1; then hyprctl dispatch movefocus r; else hyprctl dispatch changegroupactive f; fi'
--bindd = $mainMod, left, Focus left, exec, bash -c 'if hyprctl activewindow -j | jq -e "((.grouped | type) == \"boolean\") or (.address == (.grouped[0] // empty))" >/dev/null 2>&1; then hyprctl dispatch movefocus l; else hyprctl dispatch changegroupactive b; fi'

-- Move focus with mainMod + arrow keys (layout-aware)
hl.bind(mainMod .. " + left", hl.dsp.exec_cmd(scriptsDir .. "/LayoutKeybindDispatch.sh focus-left"), { description = "Focus left (layout-aware)" })
hl.bind(mainMod .. " + right", hl.dsp.exec_cmd(scriptsDir .. "/LayoutKeybindDispatch.sh focus-right"), { description = "Focus right (layout-aware)" })
hl.bind(mainMod .. " + up", hl.dsp.exec_cmd(scriptsDir .. "/LayoutKeybindDispatch.sh focus-up"), { description = "Focus up (layout-aware)" })
hl.bind(mainMod .. " + down", hl.dsp.exec_cmd(scriptsDir .. "/LayoutKeybindDispatch.sh focus-down"), { description = "Focus down (layout-aware)" })

-- Workspaces related
hl.bind(mainMod .. " + tab", hl.dsp.focus({ workspace = "m+1" }), { description = "Next workspace" })
hl.bind(mainMod .. " + SHIFT + tab", hl.dsp.focus({ workspace = "m-1" }), { description = "Previous workspace" })

-- Special workspace
hl.bind(mainMod .. " + SHIFT + U", hl.dsp.window.move({ workspace = "special" }), { description = "Move to special workspace" })
hl.bind(mainMod .. " + U", hl.dsp.workspace.toggle_special(""), { description = "Toggle special workspace" })

-- The following mappings use the key codes to better support various keyboard layouts
-- 1 is code:10, 2 is code 11, etc
-- Switch workspaces with mainMod + [0-9]
hl.bind(mainMod .. " + code:10", hl.dsp.exec_cmd(scriptsDir .. "/WorkspaceScroll.sh 1"), { description = "Workspace 1" })
hl.bind(mainMod .. " + code:11", hl.dsp.exec_cmd(scriptsDir .. "/WorkspaceScroll.sh 2"), { description = "Workspace 2" })
hl.bind(mainMod .. " + code:12", hl.dsp.exec_cmd(scriptsDir .. "/WorkspaceScroll.sh 3"), { description = "Workspace 3" })
hl.bind(mainMod .. " + code:13", hl.dsp.exec_cmd(scriptsDir .. "/WorkspaceScroll.sh 4"), { description = "Workspace 4" })
hl.bind(mainMod .. " + code:14", hl.dsp.exec_cmd(scriptsDir .. "/WorkspaceScroll.sh 5"), { description = "Workspace 5" })
hl.bind(mainMod .. " + code:15", hl.dsp.exec_cmd(scriptsDir .. "/WorkspaceScroll.sh 6"), { description = "Workspace 6" })
hl.bind(mainMod .. " + code:16", hl.dsp.exec_cmd(scriptsDir .. "/WorkspaceScroll.sh 7"), { description = "Workspace 7" })
hl.bind(mainMod .. " + code:17", hl.dsp.exec_cmd(scriptsDir .. "/WorkspaceScroll.sh 8"), { description = "Workspace 8" })
hl.bind(mainMod .. " + code:18", hl.dsp.exec_cmd(scriptsDir .. "/WorkspaceScroll.sh 9"), { description = "Workspace 9" })
hl.bind(mainMod .. " + code:19", hl.dsp.exec_cmd(scriptsDir .. "/WorkspaceScroll.sh 10"), { description = "Workspace 10" })

-- Move active window and follow to workspace mainMod + SHIFT [0-9]
hl.bind(mainMod .. " + SHIFT + code:10", hl.dsp.window.move({ workspace = 1 }), { description = "Move to workspace 1" })
hl.bind(mainMod .. " + SHIFT + code:11", hl.dsp.window.move({ workspace = 2 }), { description = "Move to workspace 2" })
hl.bind(mainMod .. " + SHIFT + code:12", hl.dsp.window.move({ workspace = 3 }), { description = "Move to workspace 3" })
hl.bind(mainMod .. " + SHIFT + code:13", hl.dsp.window.move({ workspace = 4 }), { description = "Move to workspace 4" })
hl.bind(mainMod .. " + SHIFT + code:14", hl.dsp.window.move({ workspace = 5 }), { description = "Move to workspace 5" })
hl.bind(mainMod .. " + SHIFT + code:15", hl.dsp.window.move({ workspace = 6 }), { description = "Move to workspace 6" })
hl.bind(mainMod .. " + SHIFT + code:16", hl.dsp.window.move({ workspace = 7 }), { description = "Move to workspace 7" })
hl.bind(mainMod .. " + SHIFT + code:17", hl.dsp.window.move({ workspace = 8 }), { description = "Move to workspace 8" })
hl.bind(mainMod .. " + SHIFT + code:18", hl.dsp.window.move({ workspace = 9 }), { description = "Move to workspace 9" })
hl.bind(mainMod .. " + SHIFT + code:19", hl.dsp.window.move({ workspace = 10 }), { description = "Move to workspace 10" })
hl.bind(mainMod .. " + SHIFT + bracketleft", hl.dsp.window.move({ workspace = -1 }), { description = "Move to previous workspace" })
hl.bind(mainMod .. " + SHIFT + bracketright", hl.dsp.window.move({ workspace = "+1" }), { description = "Move to next workspace" })

-- Move active window to a workspace silently mainMod + CTRL [0-9]
hl.bind(mainMod .. " + CTRL + code:10", hl.dsp.window.move({ workspace = 1, follow = false }), { description = "Move silently to workspace 1" })
hl.bind(mainMod .. " + CTRL + code:11", hl.dsp.window.move({ workspace = 2, follow = false }), { description = "Move silently to workspace 2" })
hl.bind(mainMod .. " + CTRL + code:12", hl.dsp.window.move({ workspace = 3, follow = false }), { description = "Move silently to workspace 3" })
hl.bind(mainMod .. " + CTRL + code:13", hl.dsp.window.move({ workspace = 4, follow = false }), { description = "Move silently to workspace 4" })
hl.bind(mainMod .. " + CTRL + code:14", hl.dsp.window.move({ workspace = 5, follow = false }), { description = "Move silently to workspace 5" })
hl.bind(mainMod .. " + CTRL + code:15", hl.dsp.window.move({ workspace = 6, follow = false }), { description = "Move silently to workspace 6" })
hl.bind(mainMod .. " + CTRL + code:16", hl.dsp.window.move({ workspace = 7, follow = false }), { description = "Move silently to workspace 7" })
hl.bind(mainMod .. " + CTRL + code:17", hl.dsp.window.move({ workspace = 8, follow = false }), { description = "Move silently to workspace 8" })
hl.bind(mainMod .. " + CTRL + code:18", hl.dsp.window.move({ workspace = 9, follow = false }), { description = "Move silently to workspace 9" })
hl.bind(mainMod .. " + CTRL + code:19", hl.dsp.window.move({ workspace = 10, follow = false }), { description = "Move silently to workspace 10" })
hl.bind(mainMod .. " + CTRL + bracketleft", hl.dsp.window.move({ workspace = -1, follow = false }), { description = "Move silently to previous workspace" })
hl.bind(mainMod .. " + CTRL + bracketright", hl.dsp.window.move({ workspace = "+1", follow = false }), { description = "Move silently to next workspace" })

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }), { description = "Next workspace" })
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }), { description = "Previous workspace" })
hl.bind(mainMod .. " + period", hl.dsp.focus({ workspace = "e+1" }), { description = "Next workspace" })
hl.bind(mainMod .. " + comma", hl.dsp.focus({ workspace = "e-1" }), { description = "Previous workspace" })

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { description = "Move window" })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { description = "Resize window" })

hl.on("hyprland.start", function()
    hl.exec_cmd(scriptsDir .. "/ChangeLayout.sh init")
end)

