hl.config({
	general = {
		resize_on_border = true,
		layout = "scrolling",
	},
	scrolling = {
		column_width = 0.95,
		fullscreen_on_one_column = true,
		direction = "right",
		follow_focus = true,
		focus_fit_method = 1,
		wrap_focus = true,
		wrap_swapcol = true,
	},
	dwindle = {
		preserve_split = true,
		smart_resizing = true,
		use_active_for_splits = true,
		smart_split = false,
		default_split_ratio = 1.0,
		split_bias = 0,
		precise_mouse_move = true,
		special_scale_factor = 0.8,
	},
	master = {
		new_status = "slave",
		new_on_top = false,
		new_on_active = "none",
		orientation = "left",
		mfact = 0.55,
		slave_count_for_center_master = 2,
		center_master_fallback = "left",
		smart_resizing = true,
		drop_at_cursor = true,
		always_keep_position = false,
	},
	cursor = {
		sync_gsettings_theme = true,
		no_hardware_cursors = 0,
		enable_hyprcursor = true,
		warp_on_change_workspace = 2,
		no_warps = false,
		no_break_fs_vrr = false,
		min_refresh_rate = 24,
		hotspot_padding = 1,
		inactive_timeout = 0,
		default_monitor = "",
		zoom_factor = 1.0,
		zoom_rigid = false,
		zoom_detached_camera = true,
		hide_on_key_press = true,
		hide_on_touch = false,
		hide_on_tablet = false,
		use_cpu_buffer = false,
	},
	input = {
		kb_layout = "us",
		kb_variant = "",
		kb_model = "",
		kb_options = "",
		kb_rules = "",
		repeat_rate = 50,
		repeat_delay = 300,
		sensitivity = 0,
		numlock_by_default = false,
		left_handed = false,
		follow_mouse = 1,
		float_switch_override_focus = false,
		accel_profile = "flat",
		touchpad = {
			disable_while_typing = true,
			natural_scroll = true,
			clickfinger_behavior = false,
			middle_button_emulation = false,
			tap_to_click = true,
			drag_lock = false,
		},
		touchdevice = {
			enabled = false,
		},
		tablet = {
			transform = 0,
			left_handed = 0,
		},
	},
	gestures = {
		workspace_swipe_distance = 300,
		workspace_swipe_touch = false,
		workspace_swipe_invert = false,
		workspace_swipe_min_speed_to_force = 30,
		workspace_swipe_cancel_ratio = 0.5,
		workspace_swipe_create_new = true,
		workspace_swipe_direction_lock = true,
		workspace_swipe_forever = false,
		workspace_swipe_use_r = false,
		close_max_timeout = 100,
	},
	binds = {
		workspace_back_and_forth = true,
		allow_workspace_cycles = true,
		pass_mouse_when_bound = true,
	},
	misc = {
		force_default_wallpaper = 0,
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
		vrr = 1,
		mouse_move_enables_dpms = true,
		enable_swallow = false,
		swallow_regex = "^(kitty)$",
		focus_on_activate = false,
		initial_workspace_tracking = 0,
		middle_click_paste = true,
		enable_anr_dialog = true,
		anr_missed_pings = 15,
		allow_session_lock_restore = true,
		on_focus_under_fullscreen = 1,
	},
	xwayland = {
		enabled = true,
		force_zero_scaling = true,
	},
	render = {
		direct_scanout = 0,
	},
})

hl.gesture({
	fingers = 3,
	direction = "vertical",
	action = "workspace",
})

hl.gesture({
	fingers = 4,
	direction = "down",
	action = "float",
})

-- Dynamic cursor plugin configuration
if hl.plugin.dynamic_cursors then
	hl.config({
		plugin = {
			dynamic_cursors = {
				enabled = true,
				mode = "tilt",
				threshold = 2,
				rotate = {
					length = 24,
					offset = 0.0,
				},
				tilt = {
					limit = 5000,
					activation = "negative_quadratic",
					window = 100,
					full = 120,
				},
				stretch = {
					limit = 3000,
					activation = "quadratic",
					window = 100,
				},
				shake = {
					enabled = false,
					threshold = 6.0,
					base = 4.0,
					speed = 4.0,
					influence = 0.0,
					limit = 0.0,
					timeout = 2000,
					effects = false,
					ipc = false,
				},
				hyprcursor = {
					nearest = 1,
					enabled = true,
					resolution = -1,
					fallback = "clientside",
				},
			},
		},
	})
end
