config_version = 12

[audio]
enable_sounds = true
sound_volume = 0.29999999329447746

[bar.default]
background_opacity = 0.89999997988343239
border = "outline"
end = [
    "recorder",
    "notifications",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "weather",
    "clock",
    "control-center",
    "session"
]
font_family = "JetBrainsMono Nerd Font"
font_weight = 400
margin_opposite_edge = 2
start = [ "launcher", "workspaces", "tray", "ram", "cpu", "cat" ]

[brightness]
enable_ddcutil = true
minimum_brightness = 0.39999999105930328
sync_all_monitors = true

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = [ "desktop-widget-0000000000000001" ]

    [desktop_widgets.grid]
    cell_size = 8
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 144.0
    box_width = 304.0
    cx = 1752.0
    cy = 124.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "clock"

[dock]
launcher_position = "start"
pinned = [ "steam", "equibop", "zen", "kitty" ]
reserve_space = false
show_dots = true
show_instance_count = false
show_running = false
smart_auto_hide = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 30

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 750.0

[keybinds]
down = [ "Down", "Ctrl+j" ]
left = [ "Left", "Ctrl+h" ]
right = [ "Right", "Ctrl+l" ]
up = [ "Up", "Ctrl+k" ]

[location]
auto_locate = true

[lockscreen]
blurred_desktop = true
fingerprint = false

[lockscreen_widgets]
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[nightlight]
enabled = true
force = true
temperature_day = 5100
temperature_night = 4600

[notification]
background_opacity = 0.9499999787658453
layer = "overlay"
offset_x = 4
offset_y = 4

[osd]
offset_x = 8

[plugin_settings."alexander/screen-toolkit"]
search-engine-url = "https://duckduckgo.com/?q="
x02-expiry = "1h"

[plugin_settings."kenn/keybind-cheatsheet"]
cheatsheet_open_near_click = false
hyprland_parser = "lua"
show_actions = true

[plugin_settings."noctalia/screen_recorder"]
replay_duration = 60
replay_enabled = true
resolution = "1280x720"
restore_portal = true
video_source = "focused"

[plugin_settings."tadomika_ari/config-swap"]
panel_placement = "attached"

[plugins]
enabled = [
    "tadomika_ari/config-swap",
    "noctalia/bongocat",
    "noctalia/screen_recorder",
    "noctalia/wallhaven",
    "kenn/keybind-cheatsheet",
    "alexander/screen-toolkit"
]

[shell]
app_icon_color = "primary"
clipboard_auto_paste = "off"
external_ip_enabled = true
font_family = "JetBrainsMono Nerd Font"
panel_anchor_bar = "default"
polkit_agent = true

    [shell.greeter_sync]
    auto_sync = false

    [shell.launcher]
    categories = true
    compact = true

        [shell.launcher.providers.emoji]
        global = false

    [shell.panel]
    clipboard_placement = "attached"
    floating_layer = "overlay"
    launcher_placement = "attached"
    launcher_position = "auto"
    polkit_placement = "attached"

    [shell.screen_corners]
    enabled = true
    size = 24

    [shell.screenshot]
    confirm_region = true
    directory = "~/Pictures/Screenshots"
    pipe_command = "swappy -f -"

    [shell.session]
    grid = false

    [shell.shadow]
    direction = "down_right"

[theme]
builtin = "Catppuccin"
community_palette = "Catppuccin Mocha Blue"
custom_palette = "dragon-mc"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "soft"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "gtk3", "gtk4", "hyprland", "kcolorscheme", "kitty", "qt", "starship" ]
    community_ids = [
        "opencode",
        "zen-browser",
        "discord",
        "gimp",
        "neovim",
        "heroiclauncher",
        "prismlauncher",
        "steam",
        "rofi",
        "vicinae",
        "fastfetch",
        "hyprtoolkit",
        "lazygit",
        "yazi"
    ]

[wallpaper]
fill_mode = "span"
transition_duration = 2000
transition_on_startup = true

    [wallpaper.default]
    path = "/home/gloves/Pictures/Wallpapers/Catppuccin/dragon.jpg"

    [wallpaper.last]
    path = "/home/gloves/Pictures/Wallpapers/Catppuccin/dragon.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/gloves/Pictures/Wallpapers/Catppuccin/dragon.jpg"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/gloves/Pictures/Wallpapers/Catppuccin/dragon.jpg"
    theme_mode = "dark"
    wallpaper_scheme = "soft"

[weather]
unit = "imperial"

[widget.cat]
audio_spectrum = true
input_devices = [
    "/dev/input/by-id/usb-Razer_Razer_Cynosa_Chroma-event-kbd",
    "/dev/input/by-id/usb-Razer_Razer_Cynosa_Chroma-if01-event-kbd",
    "/dev/input/by-id/usb-Razer_Razer_Naga_X-event-mouse",
    "/dev/input/by-id/usb-Razer_Razer_Naga_X-if01-event-kbd",
    "/dev/input/by-id/usb-Razer_Razer_Naga_X-if02-event-kbd"
]
tappy_mode = true
type = "noctalia/bongocat:cat"

[widget.clock]
format = "%-I:%M:%S %p  %A, %B %d"

[widget.control-center]
enabled = false
glyph = "hyprland"

[widget.launcher]
capsule_radius = "auto"
custom_image = "/home/gloves/Pictures/Assets/arch-linux.svg"
font_family = "JetBrainsMono Nerd Font"
font_weight = 400
scale = 1.6000000000000001

[widget.network]
show_label = false

[widget.ram]
stat = "ram_pct"

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.tray]
hidden = [ "Network", "Blueman" ]

[widget.weather]
show_condition = false

[widget.workspaces]
hide_when_empty = true